config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.defaults import (
    bad_request,
    page_not_found,
    permission_denied,
    server_error,
)
from django.views.generic.base import RedirectView, TemplateView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls
from wagtail_footnotes import urls as footnotes_urls

urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon/favicon.ico")),
    ),
    path("admin/", admin.site.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("comments/", include("django_comments_xtd.urls")),
    path("footnotes/", include(footnotes_urls)),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("sitemap.xml", sitemap, name="xml_sitemap"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path(
            "403/",
            permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path("404/", page_not_found, kwargs={"exception": Exception("Page not Found")}),
        path("500/", server_error),
        path("pf403/", TemplateView.as_view(template_name="portfolio/403.html")),
        path("pf404/", TemplateView.as_view(template_name="portfolio/404.html")),
        path("50x/", TemplateView.as_view(template_name="50x.html")),
    ]

    urlpatterns += i18n_patterns(
        path("400/", bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path(
            "403/",
            permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path("404/", page_not_found, kwargs={"exception": Exception("Page not Found")}),
        path("500/", server_error),
        path("pf403/", TemplateView.as_view(template_name="portfolio/403.html")),
        path("pf404/", TemplateView.as_view(template_name="portfolio/404.html")),
        path("50x/", TemplateView.as_view(template_name="50x.html")),
    )

    # Add Rosetta in debug mode only
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]


urlpatterns += i18n_patterns(
    path("comments/", include("django_comments_xtd.urls")),
    path("tools/", include("tools.urls", namespace="tools")),
    path("", include(wagtail_urls)),
)

handler403 = "portfolio.views.custom_403_view"
handler404 = "portfolio.views.custom_404_view"

tools/urls.py
from django.urls.conf import path

from tools import views

app_name = "tools"

urlpatterns = [
    path("ip/", views.IpView.as_view(), name="ip_view"),
    path("lonlat/", views.LonLatView.as_view(), name="lonlat_view"),
    path("secret/", views.GenerateSecret.as_view(), name="secret_view"),
]

tools/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from wagtail.admin.panels import FieldPanel
from wagtail.fields import StreamField

from config.abstract import PageWithHeaderAbstract
from config.blocks import STREAMFIELD_COMMON_FIELDS


class ToolsIndexPage(PageWithHeaderAbstract):
    class Meta:
        verbose_name = _("Tools Index page")

    body = StreamField(
        STREAMFIELD_COMMON_FIELDS,
        blank=True,
        use_json_field=True,
    )
    description = models.CharField(max_length=255, null=True, blank=True)

    content_panels = PageWithHeaderAbstract.content_panels + [
        FieldPanel("description"),
        FieldPanel("body"),
    ]
    subpage_types = ["tools.ToolPage"]


class ToolPage(PageWithHeaderAbstract):
    class Meta:
        verbose_name = _("Tool page")

    body = StreamField(
        STREAMFIELD_COMMON_FIELDS,
        blank=True,
        use_json_field=True,
    )
    content_panels = PageWithHeaderAbstract.content_panels + [FieldPanel("body")]
    parent_page_types = ["tools.ToolsIndexPage"]
    subpage_types = []

tools/views.py
import secrets

from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView


class IpView(TemplateView):
    template_name = "tools/ip.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        x_forwarded_for = self.request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            ip = x_forwarded_for.split(",")[0]
        else:
            ip = self.request.META.get("REMOTE_ADDR")

        context["page"] = {"title": _("My IP address")}

        context["ip"] = ip
        return context


class LonLatView(TemplateView):
    template_name = "tools/lonlat.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page"] = {"title": "Coordinates precision"}

        return context


class GenerateSecret(TemplateView):
    template_name = "tools/secret.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page"] = {"title": _("Generate secret")}

        context["secret_30"] = secrets.token_hex(30)
        context["secret_50"] = secrets.token_hex(50)
        context["secret_100"] = secrets.token_hex(100)
        return context

tools/templates/tools/ip.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-tools-index
{% endblock body_class %}

{% block extra_css %}
{% endblock extra_css %}

{% block title %}
  {{ page.title }}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "tools/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <div class="container mt-5">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li>
          <a href="{% pageurl site_navigation.root_page %}">{% translate "Tools" %}</a>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">{% translate "IP" %}</a>
        </li>
      </ul>
    </nav>
  </div>

  {% include "blocks/page_title.html" %}
  <div class="container">
    <div class="content">
      <table id="ip-info" class="table is-striped">
        <caption>{% translate "IP info" %}</caption>
        <tbody>
          <tr>
            <th>
              {% translate "Query IP" %}
            </th>
            <td>
              {{ ip }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "blocks/simple_footer.html" %}
{% endblock extra_footer %}

{% block extra_js %}
  {% sri_static "tools/js/ip.js" %}
{% endblock extra_js %}

{% block search_bar %}
{% endblock search_bar %}

tools/templates/tools/lonlat.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-tools-index
{% endblock body_class %}

{% block extra_css %}
{% endblock extra_css %}

{% block title %}
  {{ page.title }}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "tools/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <div class="container mt-5">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li>
          <a href="{% pageurl site_navigation.root_page %}">{% translate "Tools" %}</a>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">Coordinates precision</a>
        </li>
      </ul>
    </nav>
  </div>

  {% include "blocks/page_title.html" %}
  <div class="container">
    <div class="content mt-6">
      <h2>
        Coordinates precision
      </h2>
    </div>
    <form id="lonlat">
      <div class="field">
        <label class="label" for="latitude">
          Latitude
        </label>
        <div class="control">
          <input id="latitude"
                 type="number"
                 class="input"
                 type="text"
                 placeholder="latitude">
          <p id="latitude-hint" class="help">
            Number of decimal places: 0
          </p>
        </div>
      </div>

      <div class="field">
        <label class="label" for="longitude">
          Longitude
        </label>
        <div class="control">
          <input id="longitude"
                 type="number"
                 class="input"
                 type="text"
                 placeholder="longitude">
          <p id="longitude-hint" class="help">
            Number of decimal places: 0
          </p>
        </div>
      </div>
    </form>

    <div id="xkcd-comment" class="mt-6">
    </div>
  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "blocks/simple_footer.html" %}
{% endblock extra_footer %}

{% block extra_js %}
  {% sri_static "tools/js/lonlat.js" %}
{% endblock extra_js %}

{% block search_bar %}
{% endblock search_bar %}

tools/templates/tools/secret.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-tools-index
{% endblock body_class %}

{% block extra_css %}
  <style>
    p {
      overflow-wrap: break-word;
    }
  </style>
{% endblock extra_css %}

{% block title %}
  {{ page.title }}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "tools/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <div class="container mt-5">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li>
          <a href="{% pageurl site_navigation.root_page %}">{% translate "Tools" %}</a>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">{{ page.title }}</a>
        </li>
      </ul>
    </nav>
  </div>

  {% include "blocks/page_title.html" %}
  <div class="container">
    <div class="content">
      <h2>
        {% translate "Dynamic generation" %}
      </h2>
      <div class="container is-max-desktop">

        <form>
          <div class="field">
            <label for="length" class="label">
              {% translate "Length (8-256)" %}
            </label>
            <div class="control">
              <input class="input"
                     id="length"
                     name="length"
                     type="number"
                     min="8"
                     max="256"
                     value="{{ request.GET.length|default:'16' }}">
            </div>
          </div>

          <fieldset>
            <legend class="label">
              {% translate "Allowed characters sets" %}
            </legend>
            <div>
              <input type="checkbox"
                     id="use_capitals"
                     name="use_capitals"
                     {% if request.GET|length == 0 or request.GET.use_capitals %}checked{% endif %} />
              <label class="checkbox" for="use_capitals">
                {% translate "Capital letters (A-Z)" %}
              </label>
            </div>
            <div>
              <input type="checkbox"
                     id="use_lowercase"
                     name="use_lowercase"
                     {% if request.GET|length == 0 or request.GET.use_lowercase %}checked{% endif %} />
              <label class="checkbox" for="use_lowercase">
                {% translate "Lowercase letters (a-z)" %}
              </label>
            </div>
            <div>
              <input type="checkbox"
                     id="use_numbers"
                     name="use_numbers"
                     {% if request.GET|length == 0 or request.GET.use_numbers %}checked{% endif %} />
              <label class="checkbox" for="use_numbers">
                {% translate "Numbers (0-9)" %}
              </label>
            </div>
            <div>
              <input type="checkbox"
                     id="use_special"
                     name="use_special"
                     {% if request.GET|length == 0 or request.GET.use_special %}checked{% endif %} />
              <label class="checkbox" for="use_special">
                {% translate "Special characters" %}
              </label>
            </div>
          </fieldset>

          <div class="control mt-2">
            <button id="form-submit" class="button is-primary">
              {% translate "Create secret" %}
            </button>
          </div>
        </form>
        <div class="columns is-mobile is-centered is-hidden" id="result-wrapper">
          <div class="column is-half">
            <div class="field has-addons">
              <div class="control">
                <input class="input" type="text" id="result">
              </div>
              <div class="control">
                <button id="copyButton" class="button is-primary">
                  {% translate "Copy" %}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h2>
        {% translate "Back-end generated" %}
      </h2>
      <h3>
        30
      </h3>
      <p>
        {{ secret_30 }}
      </p>
      <h3>
        50
      </h3>
      <p>
        {{ secret_50 }}
      </p>
      <h3>
        100
      </h3>
      <p>
        {{ secret_100 }}
      </p>
    </div>
  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "blocks/simple_footer.html" %}
{% endblock extra_footer %}

{% block extra_js %}
  {% sri_static "tools/js/secret.js" %}
{% endblock extra_js %}

{% block search_bar %}
{% endblock search_bar %}

tools/templates/tools/tool_page.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-tools-index
{% endblock body_class %}

{% block extra_css %}
{% endblock extra_css %}

{% block title %}
  {{ page.title }}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "tools/blocks/header.html" %}
{% endblock header %}

{% block content %}
  {% include "blocks/page_title.html" %}

  <div class="container">
    <div class="content">
      {% for block in page.body %}
        {% include_block block %}
      {% endfor %}

      {% if page.get_children %}
        {% include "pages/blocks/subpages_list.html" %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "blocks/simple_footer.html" %}
{% endblock extra_footer %}

tools/templates/tools/tools_index_page.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-tools-index
{% endblock body_class %}

{% block extra_css %}
{% endblock extra_css %}

{% block title %}
  {{ page.title }}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "tools/blocks/header.html" %}
{% endblock header %}

{% block content %}
  {% include "blocks/page_title.html" %}

  <div class="container mt-6">
    <div class="content">
      {% for block in page.body %}
        {% include_block block %}
      {% endfor %}
      <h2>
        {% translate "Direct link to the tools" %}
      </h2>
      <ul>
        <li>
          <a href="{% url 'tools:ip_view' %}">IP</a>
        </li>
        <li>
          <a href="{% url 'tools:lonlat_view' %}">{% translate "Coordinates precision" %}</a>
        </li>
        <li>
          <a href="{% url 'tools:secret_view' %}">{% translate "Generate secret" %}</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "blocks/simple_footer.html" %}
{% endblock extra_footer %}