config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.defaults import (
    bad_request,
    page_not_found,
    permission_denied,
    server_error,
)
from django.views.generic.base import RedirectView, TemplateView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls
from wagtail_footnotes import urls as footnotes_urls

urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon/favicon.ico")),
    ),
    path("admin/", admin.site.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("comments/", include("django_comments_xtd.urls")),
    path("footnotes/", include(footnotes_urls)),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("sitemap.xml", sitemap, name="xml_sitemap"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path(
            "403/",
            permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path("404/", page_not_found, kwargs={"exception": Exception("Page not Found")}),
        path("500/", server_error),
        path("pf403/", TemplateView.as_view(template_name="portfolio/403.html")),
        path("pf404/", TemplateView.as_view(template_name="portfolio/404.html")),
        path("50x/", TemplateView.as_view(template_name="50x.html")),
    ]

    urlpatterns += i18n_patterns(
        path("400/", bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path(
            "403/",
            permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path("404/", page_not_found, kwargs={"exception": Exception("Page not Found")}),
        path("500/", server_error),
        path("pf403/", TemplateView.as_view(template_name="portfolio/403.html")),
        path("pf404/", TemplateView.as_view(template_name="portfolio/404.html")),
        path("50x/", TemplateView.as_view(template_name="50x.html")),
    )

    # Add Rosetta in debug mode only
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]


urlpatterns += i18n_patterns(
    path("comments/", include("django_comments_xtd.urls")),
    path("tools/", include("tools.urls", namespace="tools")),
    path("", include(wagtail_urls)),
)

handler403 = "portfolio.views.custom_403_view"
handler404 = "portfolio.views.custom_404_view"

tools/urls.py
from django.urls.conf import path

from tools import views

app_name = "tools"

urlpatterns = [
    path("ip/", views.IpView.as_view(), name="ip_view"),
    path("lonlat/", views.LonLatView.as_view(), name="lonlat_view"),
    path("secret/", views.GenerateSecret.as_view(), name="secret_view"),
]

external/models.py
import os

from django.db import models
from django.utils.translation import gettext_lazy as _
from wagtail.images.models import Image
from wagtail.search import index

from external.utils import commons_tag
from gallery.constants import LICENSE_CHOICES
from gallery.models import ImagePage


class CommonsFile(index.Indexed, models.Model):
    title = models.CharField(_("Title"), max_length=255)
    file_url = models.URLField(_("File URL"), max_length=255)
    commons_id = models.CharField(_("Title"), max_length=255, blank=True)
    description_url = models.URLField(_("Description URL"), max_length=255)
    description = models.TextField(_("Description"), blank=True)
    file_license = models.CharField(
        _("File license"), choices=LICENSE_CHOICES, max_length=15, blank=True
    )
    upload_date = models.DateTimeField(_("Upload date"))
    photograph_date = models.DateTimeField(_("Photograph date"), null=True)
    import_ok = models.BooleanField(_("Import OK"), blank=True, null=True)
    local_page = models.ForeignKey(
        ImagePage,
        on_delete=models.SET_NULL,
        verbose_name=_("Local page"),
        blank=True,
        null=True,
    )
    local_file = models.ForeignKey(
        Image,
        on_delete=models.SET_NULL,
        verbose_name=_("Local file"),
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    @property
    def display_title(self):
        title = os.path.splitext(self.title)[0]
        return title.replace("_", " ")

    @property
    def display_licence(self):
        return self.file_license.upper()

    @property
    def display_ext(self):
        return os.path.splitext(self.title)[1][1:].lower()

    def __str__(self):
        return self.display_title

    def save(self, *args, **kwargs):
        if self.local_page and not (self.import_ok and self.local_file):
            self.import_ok = True
            self.local_file = self.local_page.image

            self.local_page.tags.add(commons_tag())

            self.local_page.save()

        super().save(*args, **kwargs)

    search_fields = [
        index.SearchField("title"),
        index.SearchField("description"),
        index.AutocompleteField("title"),
    ]

    class Meta:
        verbose_name = _("Wikimedia Commons file")
        verbose_name_plural = _("Wikimedia Commons files")

gallery/models.py
import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Count
from django.db.models.expressions import F
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils import feedgenerator, timezone
from django.utils.html import mark_safe, strip_tags
from django.utils.translation import get_language, gettext_lazy as _
from django_comments.moderation import CommentModerator
from django_comments_xtd.models import XtdComment
from django_comments_xtd.moderation import moderator
from modelcluster.fields import ParentalManyToManyField
from modelcluster.tags import ClusterTaggableManager
from taggit.models import Tag, TaggedItemBase
from unidecode import unidecode
from wagtail.admin.panels import (
    FieldPanel,
    FieldRowPanel,
    MultiFieldPanel,
)
from wagtail.contrib.routable_page.models import RoutablePageMixin, path
from wagtail.contrib.search_promotions.models import Query
from wagtail.fields import RichTextField, StreamField
from wagtail.images import get_image_model_string
from wagtail.models import Page, ParentalKey, TranslatableMixin
from wagtail.search import index

from blog.abstract import limit_author_choices
from blog.models import COMMENTS_APP, COMMENTS_CLOSE_AFTER
from blog.services.unique_slugify import unique_slugify
from config.abstract import PageWithHeaderAbstract
from config.blocks import AlertBlock
from config.constants import LIMITED_RICHTEXTFIELD_FEATURES
from config.utils import paginate_queryset
from gallery.constants import LICENSE_CHOICES
from gallery.utils import (
    get_license_url,
    image_exif,
    improve_camera_model,
    list_albums_for_queryset,
)


class GalleryIndex(RoutablePageMixin, PageWithHeaderAbstract):
    description = models.CharField(max_length=255, null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("description", heading=_("Description")),
    ]

    feed_posts_limit = models.PositiveSmallIntegerField(
        default=20,  # type: ignore
        validators=[MaxValueValidator(100), MinValueValidator(1)],
        verbose_name=_("Post limit in the RSS/Atom feeds"),
    )

    class Meta:
        verbose_name = _("Gallery index")

    subpage_types = ["gallery.ImageCollection"]

    settings_panels = PageWithHeaderAbstract.settings_panels + [
        FieldPanel("feed_posts_limit"),
    ]

    @property
    def get_gallery_index(self):
        """
        Used to make the behaviour consistent across all pages that use
        the album_card.html templates
        """
        return self

    def get_image_collections(self):
        """
        Returns a Queryset of live children of the ImageCollection type
        """
        return ImageCollection.objects.live().child_of(self)

    def get_images(self):
        """
        Returns a Queryset of live descendants of the ImagePage type
        """
        return (
            ImagePage.objects.live()
            .descendant_of(self)
            .prefetch_related(
                "tagged_items__tag",
                "gallery_albums",
                "date__year",
            )
            .order_by("-date")
        )

    def list_featured_albums(self) -> list:
        posts = self.get_images()
        return list_albums_for_queryset(posts, featured_only=True)

    def list_albums(self) -> list:
        posts = self.get_images()
        return list_albums_for_queryset(posts)

    def list_tags(self, min_count: int = 1) -> list:
        posts = self.get_images()
        return (
            posts.values(tag_name=F("tags__name"), tag_slug=F("tags__slug"))
            .annotate(tag_count=Count("tag_slug"))
            .filter(tag_count__gte=min_count)
            .order_by("-tag_count")
        )

    def list_years(self) -> list:
        """
        Returns a list with years and image count per year
        """
        return (
            self.get_images()
            .values(year=models.F("date__year"))
            .annotate(year_count=models.Count("year"))
            .order_by("-year")
        )

    def get_context(self, request, *args, **kwargs):
        context = super(GalleryIndex, self).get_context(request, *args, **kwargs)
        images = self.get_images()

        # Pagination
        images, paginator = paginate_queryset(
            images, request, limit_setting="GALLERY_PAGINATION_PER_PAGE"
        )

        context["images"] = images
        context["paginator"] = paginator
        context["COMMENTS_APP"] = COMMENTS_APP

        return context

    def list_latest_comments(self, number: int) -> list:
        """
        Returns the <number> latest comments from the whole gallery, identified by its
        index page
        """
        results = []
        pages = self.get_images().values_list("id", flat=True)
        content_type_id = ContentType.objects.get_for_model(ImagePage).id
        comments = XtdComment.objects.filter(
            content_type_id=content_type_id,
            is_public=True,
            is_removed=False,
            object_pk__in=list(pages),
        ).order_by("-submit_date")[:number]

        for comment in comments:
            results.append(
                {
                    "user_name": comment.user_name,
                    "comment": comment.comment,
                    "date": comment.submit_date,
                    "page": ImagePage.objects.get(id=comment.object_pk),
                }
            )

        return results

    def feed_posts(self, feed, request):
        """
        Returns the posts for a RSS or ATOM feed relative to the parameters
        """
        posts = self.get_images()

        album = request.GET.get("album")
        if album:
            album = get_object_or_404(GalleryAlbum, slug=album, locale=self.locale)
            posts = posts.filter(gallery_albums__slug=album.slug)

        limit = int(request.GET.get("limit", self.feed_posts_limit))
        posts = posts[:limit]

        for post in posts:
            feed.add_item(
                post.title,
                post.full_url,
                pubdate=post.date,
                description=post.search_description,
            )

        return feed

    @path("rss/", name="rss_feed")
    def rss_view(self, request: HttpRequest) -> HttpResponse:
        """
        Return the current blog as a RSS feed
        """

        if self.seo_title:
            title = self.seo_title
        else:
            title = self.title

        feed = feedgenerator.Rss201rev2Feed(
            title=title,
            link=self.get_full_url(),
            description=self.search_description,
            language=self.locale.language_code,
            feed_url=f"{self.get_full_url()}{self.reverse_subpage('rss_feed')}",
        )
        feed = self.feed_posts(feed, request)

        response = HttpResponse(
            feed.writeString("UTF-8"), content_type="application/xml"  # type: ignore
        )
        return response

    @path("atom/", name="atom_feed")
    def atom_view(self, request: HttpRequest) -> HttpResponse:
        """
        Return the current blog as an Atom feed
        """

        if self.seo_title:
            title = self.seo_title
        else:
            title = self.title

        feed = feedgenerator.Atom1Feed(
            title=title,
            link=self.get_full_url(),
            description=self.search_description,
            language=self.locale.language_code,
            feed_url=f"{self.get_full_url()}{self.reverse_subpage('atom_feed')}",
        )
        feed = self.feed_posts(feed, request)

        response = HttpResponse(
            feed.writeString("UTF-8"), content_type="application/xml"  # type: ignore
        )
        return response

    @path("albums/", name="albums_list")
    def albums_list(self, request: HttpRequest) -> HttpResponse:
        return self.render(
            request,
            context_overrides={"albums": self.list_albums()},
            template="gallery/albums_list_page.html",
        )

    @path("albums/<slug:album>/", name="album_detail")
    def album_detail(self, request: HttpRequest, album) -> HttpResponse:
        album = get_object_or_404(GalleryAlbum, slug=album, locale=self.locale)

        images = self.get_images().filter(gallery_albums__slug=album.slug)

        images, paginator = paginate_queryset(
            images, request, limit_setting="GALLERY_PAGINATION_PER_PAGE"
        )

        return self.render(
            request,
            context_overrides={
                "album": album,
                "paginator": paginator,
                "images": images,
            },
        )

    @path("archives/", name="archives_list")
    def archives_list(self, request: HttpRequest) -> HttpResponse:
        years = sorted(set(self.get_images().values_list("date__year", flat=True)))
        return self.render(
            request,
            context_overrides={"years": years},
            template="gallery/years_list_page.html",
        )

    @path("archives/<int:year>/", name="archive_year")
    @path(_("archives/current/"), name="archive_current_year")
    def archive_year(self, request: HttpRequest, year=None) -> HttpResponse:
        if year is None:
            year = timezone.now().year
        images = self.get_images().filter(date__year=year)

        years = sorted(set(self.get_images().values_list("date__year", flat=True)))
        index = years.index(year)

        if index == 0:
            previous_year = None
        else:
            previous_year = years[index - 1]

        if index == len(years) - 1:
            next_year = None
        else:
            next_year = years[index + 1]

gallery/templates/gallery/albums_list_page.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags sri %}
{% block body_class %}
  template-albums-page
{% endblock body_class %}

{% block title %}
  Albums
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "gallery/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <section class="container mt-6">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li>
          <a href="{% pageurl site_navigation.gallery.index %}">{% translate "Gallery" %}</a>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">{% translate "Albums" %}</a>
        </li>
      </ul>
    </nav>

    <div class="content">
      <h2>
        {% translate "Albums" %}
      </h2>
    </div>

    {% include "gallery/blocks/albums_list.html" with albums=albums %}
  </section>
{% endblock content %}

{% block extra_footer %}
  {% include "gallery/blocks/gallery_footer.html" %}
{% endblock extra_footer %}

gallery/templates/gallery/image_collection.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags wagtailroutablepage_tags sri %}
{% block body_class %}
  template-gallery-index
{% endblock body_class %}

{% block header %}
  {% include "gallery/blocks/header.html" %}
{% endblock header %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block content %}
  {% if page.header_image %}
    {% image page.header_image width-1200 as header_image %}
    <div class="hero is-medium is-dark has-background ash-hero-background-image"
         style="background-image: url({{ header_image.url }});
                {{ header_image.background_position_style }}">
      <div class="hero-body">
      </div>
    </div>
  {% endif %}

  <div class="container mt-5">
    {% include "blocks/breadcrumbs.html" %}
    <h1 class="title has-text-centered">
      {{ self.title }}
    </h1>
  </div>

  <div class="container mt-6 content">
    {% for block in page.body %}
      {% if block.block_type == "services" %}
        <div class="columns is-multiline">
          {% for box in block.value %}
            <div class="column is-half">
              {% include_block box %}
            </div>
          {% endfor %}
        </div>
      {% else %}
        <div class="content">
          {% include_block block %}
        </div>
      {% endif %}
    {% endfor %}
  </div>

  {# First page only #}
  {% if self.list_albums and images.number == 1 %}
    <section class="container mt-6">
      <div class="content">
        <h2>
          {% translate "Featured albums" %}
        </h2>
      </div>
      {% include "gallery/blocks/albums_list.html" with albums=self.list_featured_albums %}
      <div class="level">
        <div class="level-item has-text-centered mt-4">
          <a href="{% routablepageurl page.get_gallery_index.specific 'albums_list' %}"
             class="button is-primary">
            <span class="icon">
              <i class="ri-gallery-fill" aria-hidden="true"></i>
            </span>
            <span>{% translate "See all albums" %}</span>
          </a>
        </div>
      </div>
    </section>
  {% endif %}

  <section class="container mt-6">
    <div class="content">
      <h2>
        {% translate "Images" %}
      </h2>
    </div>
    {% include "gallery/blocks/images_list.html" with page_slug=page.slug images=images %}
  </section>

  {% include "blocks/pagination_index.html" with page_obj=images %}
{% endblock content %}

{% block extra_footer %}
  {% include "gallery/blocks/gallery_footer.html" %}
{% endblock extra_footer %}

gallery/templates/gallery/image_page.html
{% extends "_base.html" %}
{% load wagtailcore_tags wagtailimages_tags wagtailroutablepage_tags i18n %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block social_media %}
  <meta property="og:site_name" content="{{ request.get_host }}" />
  <meta property="og:title"
        content="{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="{{ page.full_url }}" />
  <meta property="og:description" content="{{ self.search_description }}" />
  <meta property="og:locale" content="fr" />

  <meta name="twitter:site" content="@ash_crow" />
  <meta name="twitter:title"
        content="{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}" />
  <meta name="twitter:description" content="{{ self.search_description }}" />
  <meta name="twitter:card" content="summary_large_image" />

  {% image self.image fill-1200x627 as header_image %}
  <meta property="og:image" content="{{ header_image.full_url }}" />
  <meta name="twitter:image" content="{{ header_image.full_url }}" />
  <meta property="og:image:alt " content="{{ self.alt_text }}" />
{% endblock social_media %}

{% block header %}
  {% include "gallery/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <article>
    <div class="container mt-5">
      {% include "blocks/breadcrumbs.html" %}
      <h1 class="title has-text-centered">
        {{ self.title }}
      </h1>
    </div>

    <div class="mt-2 mb-5">
      <div class="content has-text-centered">
        {% if self.date %}
          <span class="icon-text">
            <span class="icon">
              <i class="ri-calendar-fill" aria-hidden="true"></i>
            </span>
            <span><time datetime="{{ self.date |date:'Y-m-d H:i:s e' }}">{{ self.date }}</time></span>
          </span>
          {% if self.author %}
            <span class="icon-text">
              <span class="icon">
                <i class="ri-user-3-fill" aria-hidden="true"></i>
              </span>
              <span>
                <a href="{% routablepageurl page.get_gallery_index.specific 'author_detail' author=self.author.username %}">{{ self.author.username }}</a>
              </span>
            </span>
          {% endif %}
          {% if self.imported_likes %}
            <span class="icon-text">
              <span class="icon">
                <i class="ri-heart-fill" aria-hidden="true"></i>
              </span>
              {% translate "Likes/faves received on the original publication" as likes_faves_label %}
              <span title="{{ likes_faves_label }}">{{ self.imported_likes }}</span>
            </span>
          {% endif %}
        {% endif %}
        {% if self.get_translations.live %}
          <span class="icon-text">
            <span class="icon">
              <i class="ri-translate ri-lg" aria-hidden="true"></i>
            </span>
            <span>
              {% for translation in self.get_translations.live %}
                {% get_language_info for translation.locale.language_code as lang %}
                <a href="{% pageurl translation %}"
                   rel="alternate"
                   hreflang="{{ language_code }}">{{ lang.name_local | title }}</a>
              {% endfor %}
            </span>
          </span>
        {% endif %}
      </div>
    </div>

    <div id="gallery-body" class="container">
      <div class="columns is-mobile">
        <div class="column is-three-fifths is-offset-one-fifth">
          {% for block in page.body %}
            {% include_block block %}
          {% endfor %}
        </div>
      </div>

      <div id="gallery-image" class="card mt-4 mb-6">
        <div class="card-image px-4 py-4">
          {% include "blocks/image_with_caption.html" with image=self.image alt=self.alt_text %}
        </div>
        <div class="card-content">
          <div class="content">
            {{ self.caption|richtext }}
            {% if self.file_license %}
              <p>
                <span class="icon-text">
                  <span class="icon">
                    <i class="ri-copyright-line ri-lg" aria-hidden="true"></i>
                  </span>
                  <span>
                    {% translate "License:" %} 
                    {% if self.get_license_url %}
                      <a href="{{ self.get_license_url }}"
                         target="_blank"
                         rel="noopener noreferrer">
                        {{ self.get_file_license_display }}
                        <span class="is-sr-only">{% translate "(opens in a new tab)" %}</span>
                      </a>
                    {% else %}
                      {{ self.get_file_license_display }}
                    {% endif %}
                  </span>
                </span>
              </p>
            {% endif %}
            {% if self.geo_lon and self.geo_lat %}
              <p>
                <span class="icon-text">
                  <span class="icon">
                    <i class="ri-earth-line ri-lg" aria-hidden="true"></i>
                  </span>
                  <span>
                    {% translate "Coordinates:" %} 
                    <a href="{{ self.get_coord_url }}"
                       target="_blank"
                       rel="noopener noreferrer">{{ self.geo_lat }}, {{ self.geo_lon }}</a>
                  </span>
                </span>
              </p>
            {% endif %}
            {% if self.get_photo_details %}
              <p>
                <span class="icon-text">
                  <span class="icon">
                    <i class="ri-camera-line ri-lg" aria-hidden="true"></i>
                  </span>
                  <span>{{ self.get_photo_details|safe }}</span>
                </span>
                {% if request.user.is_active and request.user.is_staff %}
                  <button class="button is-small open-modal"
                          id="open-modal-metadata-{{ self.image.id }}">
                    <span class="icon">
                      <i class="ri-camera-lens-line ri-lg"></i>
                    </span>
                    <span>{% translate "View image metadata" %}</span>
                  </button>
                {% endif %}
              </p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="meta container">
      <div class="tags">
        {% if self.tags.all %}
          <span class="icon-text">
            <span class="icon">
              <i class="ri-price-tag-3-fill" aria-hidden="true"></i>
            </span>
            <span>{% translate "Tags:" %}</span>
          </span>

          <div class="tags my-5">
            {% for tag in self.tags.all|dictsort:"slug" %}
              <a class="tag"
                 href="{% routablepageurl page.get_gallery_index.specific 'tag_detail' tag=tag.slug %}">{{ tag }}</a>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      {% if self.list_albums %}
        <div class="content">
          <h2>
            {% translate "Albums" %}
          </h2>
        </div>
        {% include "gallery/blocks/albums_list.html" with albums=self.list_albums %}
      {% endif %}
    </div>

  </article>
  {% translate "More images" as post_pagination_label %}
  {% include "blocks/pagination_post.html" with label=post_pagination_label %}

  {% if COMMENTS_APP == "django_comments_xtd" %}
    {% include "blog/blocks/blog_post_comments_xtd.html" with blog=self %}
  {% endif %}

  {% if request.user.is_active and request.user.is_staff %}
    <dialog class="modal"
            id="modal-metadata-{{ self.image.id }}"
            aria-modal="true"
            aria-labelledby="caption-{{ self.image.id }}">
      <div class="modal-background">
      </div>
      <div class="modal-card">
        <header class="modal-card-head">
          <h1 class="modal-card-title">
            Métadonnées
          </h1>
          <button class="delete ash-modal-close" aria-label="close">
          </button>
        </header>
        <section class="modal-card-body">
          <table class="table is-striped is-hoverable is-fullwidth">
            <caption>
              EXIF
            </caption>
            <tbody>
              {% for key, value in self.get_exif.items %}
                <tr>
                  <th scope="row">
                    {{ key }}
                  </th>
                  <td>
                    {{ value }}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </section>
      </div>
    </dialog>
  {% endif %}
{% endblock content %}

{% block extra_footer %}
  {% include "gallery/blocks/gallery_footer.html" %}
{% endblock extra_footer %}

gallery/templates/gallery/search.html
{% extends "_base.html" %}
{% load i18n static wagtailcore_tags sri %}

{% block body_class %}
  template-searchresults
{% endblock body_class %}

{% block title %}
  {% translate "Search in gallery" %}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
  {% if paginator.num_pages > 1 %}
    — Page {{ search_results.number }}/{{ paginator.num_pages }}
  {% endif %}
{% endblock title_suffix %}

{% block header %}
  {% include "gallery/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <div class="container">
    <div class="content mt-6">
      <h1>
        {% translate "Search in gallery" %}
      </h1>
      {% include "blocks/search_form.html" with search_page=search_url htmx_on=1 %}
    </div>

    {% include "gallery/blocks/search_results.html" with search_results=search_results search_query=search_query %}

  </div>
{% endblock content %}

{% block extra_footer %}
  {% include "gallery/blocks/gallery_footer.html" %}
{% endblock extra_footer %}

{% block extra_js %}
  {% sri_static "lib/htmx/htmx.2.0.4.min.js" %}
{% endblock extra_js %}

gallery/templates/gallery/tags_list_page.html
{% extends "_base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags wagtailroutablepage_tags sri %}
{% block body_class %}
  template-albums-page
{% endblock body_class %}

{% block title %}
  {% translate "Tags" %}
{% endblock title %}

{% block title_suffix %}
  {% wagtail_site as current_site %}
  — {{ current_site.hostname }}
{% endblock title_suffix %}

{% block header %}
  {% include "gallery/blocks/header.html" %}
{% endblock header %}

{% block content %}
  <section class="container mt-6">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li>
          <a href="{% pageurl site_navigation.gallery.index %}">{% translate "Gallery" %}</a>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">{% translate "Tags" %}</a>
        </li>
      </ul>
    </nav>

    <div class="content">
      <h2>
        {% translate "Tags" %}
      </h2>
      <div class="buttons has-addons is-centered">
        {% for first_letter in sorted_tags.keys|dictsort:0 %}
          <a href="#{{ first_letter }}" class="button is-link is-light">{{ first_letter }}</a>
        {% endfor %}
      </div>

      {% for first_letter, tags in sorted_tags.items|dictsort:0 %}
        <h2 id="{{ first_letter }}">
          {{ first_letter }}
        </h2>
        <ul class="ash-columns">
          {% for tag in tags|dictsort:"tag_slug" %}
            <li>
              <a href="{% routablepageurl page 'tag_detail' tag=tag.tag_slug %}"><strong>{{ tag.tag_name }}</strong> ({{ tag.tag_count }})</a>
            </li>
          {% endfor %}
        </ul>
      {% endfor %}
    </div>
  </section>
{% endblock content %}

{% block extra_footer %}
  {% include "gallery/blocks/gallery_footer.html" %}
{% endblock extra_footer %}